# Generated by Django 4.0.5 on 2022-06-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='fname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='lname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
