# Generated by Django 4.0.5 on 2022-06-03 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_address_fname_address_lname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='fname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='lname',
            new_name='lastname',
        ),
    ]
