# Generated by Django 4.0.5 on 2022-06-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_rename_fname_address_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='firstname',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='lastname',
            new_name='lname',
        ),
    ]
