# Generated by Django 4.0.5 on 2022-06-07 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_remove_address_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='fname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='homeNum',
            new_name='home_number',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='lname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='workNum',
            new_name='mobile_number',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='mobileNum',
            new_name='work_number',
        ),
    ]
