# Generated by Django 4.0.5 on 2022-06-08 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_rename_fname_address_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
